apiVersion: v1
kind: Pod
metadata:
  name: checker
  labels:
    app.kubernetes.io/name: checker
spec:
  serviceAccount: checker
  containers:
  - name: checker
    image: georgesnd/test
    ports:
    - containerPort: 4000
      name: checker-port


