apiVersion: v1
kind: Service
metadata:
  name: checker-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: checker
  ports:
  - name: checker-service-port
    protocol: TCP
    port: 80
    targetPort: checker-port
    nodePort: 31000